<a href="https://colab.research.google.com/github/Meenakshi2434/Machine-Learning/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#assign inputvalues
input_value = np.array([[0,0],[0,1], [1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [4]:
#assign outputvalues
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

In [5]:
#assign weights
weights = np.array([[0,1],[0,2]])
weights

array([[0, 1],
       [0, 2]])

In [6]:
 #add bias
 bias = 0.3

In [10]:
#activation function
def sigmoid_func(x):
  return 1/(1 + np.exp(-x))

In [8]:
#derivative ofsigmoid function
def der(x):
  return sigmoid_func(x) * (1- sigmoid_func(x))

In [12]:
#updating weights
for epochs in range(10000):
  input_arr = input_value
  weighted_sum = np.dot(input_arr, weights) + bias
  first_output = sigmoid_func(weighted_sum)

  error = first_output - output
  total_error = np.square(np.subtract(first_output, output)).mean()
  #print(total_error)

  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der
  t_input = input_value.T
  final_derivative = np.dot(t_input, derivative)

  #update weights
  weights = weights - 0.05 * final_derivative
  #update bias
  for i in derivative:
    bias = bias - 0.05 * i

print(weights)
print(bias)


[[-0.42137356 -0.39626666]
 [ 8.98554437  9.02992205]]
[-4.19429251 -4.23156307]


In [13]:
#predictions
pred = np.array([0,1])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)

print(res)

[0.9917663  0.99182413]


In [14]:
#predictions
pred = np.array([0,0])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)

print(res)

[0.01485734 0.01432157]
